"""E类: 缠论连续值因子定义。"""

from xqtrader.domain.factor.definitions.factor_def import FactorDefinition as F

CHAN_FACTORS: list[F] = [
    F(factor_id="chan_fractal_strength", display_name="分型强度", category="chan",
      group_id="chan_fractal", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low", description="极值与两侧差之和, 分型显著度"),
    F(factor_id="chan_bi_length", display_name="笔长度", category="chan",
      group_id="chan_bi", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low", description="abs(顶H-底L), 趋势幅度"),
    F(factor_id="chan_bi_kcount", display_name="笔内K线数", category="chan",
      group_id="chan_bi", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low", description="一笔内K线数, 趋势持续"),
    F(factor_id="chan_bi_slope", display_name="笔斜率", category="chan",
      group_id="chan_bi", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close", description="(终点价-起点价)/K线数*100, 趋势强度"),
    F(factor_id="chan_bi_amplitude", display_name="笔振幅", category="chan",
      group_id="chan_bi", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low", description="笔内最大回撤/笔长度, 趋势质量"),
    F(factor_id="chan_bi_strength", display_name="笔强度", category="chan",
      group_id="chan_bi", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low", description="笔长度/笔内K线数, 趋势效率"),
    F(factor_id="chan_zs_zg", display_name="中枢上沿ZG", category="chan",
      group_id="chan_zs", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="high,low", description="min(各笔最高价), 阻力位"),
    F(factor_id="chan_zs_zd", display_name="中枢下沿ZD", category="chan",
      group_id="chan_zs", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="high,low", description="max(各笔最低价), 支撑位"),
    F(factor_id="chan_zs_range", display_name="中枢区间", category="chan",
      group_id="chan_zs", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="high,low", description="ZG-ZD, 震荡幅度"),
    F(factor_id="chan_zs_height_ratio", display_name="中枢高度比", category="chan",
      group_id="chan_zs", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="high,low,close", description="(ZG-ZD)/price, 标准化中枢"),
    F(factor_id="chan_divergence_ratio", display_name="背驰强度", category="chan",
      group_id="chan_div", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close,high,low", description="A_curr/A_prev面积比, 背驰程度"),
    F(factor_id="chan_macd_area", display_name="MACD面积", category="chan",
      group_id="chan_div", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=35,
      dependencies="close", description="笔内MACD柱状图绝对值之和, 动能衰减"),
]
