"""B类: 基本面因子定义。"""

from xqtrader.domain.factor.definitions.factor_def import FactorDefinition as F

FUNDAMENTAL_FACTORS: list[F] = [
    # B1 价值因子 (daily_derived, 从 daily_indicator 读取)
    F(factor_id="pe_ttm", display_name="市盈率TTM", category="fundamental",
      group_id="value", direction="ASC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="pe_ttm", description="总市值/净利润TTM"),
    F(factor_id="ep_ttm", display_name="盈利收益率TTM", category="fundamental",
      group_id="value", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily_derived",
      dependencies="pe_ttm", description="1/PE_TTM, Barra Earnings Yield核心项"),
    F(factor_id="pb", display_name="市净率", category="fundamental",
      group_id="value", direction="ASC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="pb", description="daily_indicator.pb"),
    F(factor_id="bp", display_name="账面市值比", category="fundamental",
      group_id="value", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily_derived",
      dependencies="pb", description="1/PB, Barra Book-to-Price"),
    F(factor_id="ps_ttm", display_name="市销率TTM", category="fundamental",
      group_id="value", direction="ASC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="ps_ttm", description="daily_indicator.ps_ttm"),
    F(factor_id="sp_ttm", display_name="销售收益率TTM", category="fundamental",
      group_id="value", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily_derived",
      dependencies="ps_ttm", description="1/PS_TTM, 销售估值"),
    F(factor_id="pe", display_name="市盈率(动态)", category="fundamental",
      group_id="value", direction="ASC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="pe", description="短期估值"),
    F(factor_id="ps", display_name="市销率(动态)", category="fundamental",
      group_id="value", direction="ASC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="ps", description="短期估值"),
    F(factor_id="dv_ratio", display_name="股息率(%)", category="fundamental",
      group_id="value", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="dv_ratio", description="分红收益"),
    F(factor_id="dv_ttm", display_name="股息率TTM(%)", category="fundamental",
      group_id="value", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="dv_ttm", description="分红收益TTM"),
    F(factor_id="cfp", display_name="现金收益率", category="fundamental",
      group_id="value", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="quarterly", report_lag_days=120,
      dependencies="n_cashflow_act,total_mv", description="经营现金流/总市值, Barra Cash EY"),
    # B2 盈利因子 (quarterly, 从 fina_indicator PIT 读取)
    F(factor_id="roe", display_name="净资产收益率", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="roe", description="核心盈利"),
    F(factor_id="roe_waa", display_name="加权平均ROE", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="roe_waa", description="杜邦分析"),
    F(factor_id="roe_dt", display_name="ROE(扣非)", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="roe_dt", description="剔除非经常"),
    F(factor_id="roa", display_name="总资产报酬率", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="roa", description="资产效率"),
    F(factor_id="roic", display_name="投入资本回报率", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="roic", description="资本效率"),
    F(factor_id="grossprofit_margin", display_name="销售毛利率", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="grossprofit_margin", description="毛利水平"),
    F(factor_id="netprofit_margin", display_name="销售净利率", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="netprofit_margin", description="净利水平"),
    F(factor_id="eps", display_name="基本每股收益", category="fundamental",
      group_id="profitability", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="eps", description="每股盈利"),
    # B3 成长因子
    F(factor_id="q_or_yoy", display_name="营收同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_or_yoy", description="营收增长"),
    F(factor_id="q_netprofit_yoy", display_name="净利润同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_netprofit_yoy", description="利润增长"),
    F(factor_id="q_dtprofit_yoy", display_name="扣非净利润同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_dtprofit_yoy", description="核心利润增长"),
    F(factor_id="q_op_yoy", display_name="营业利润同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_op_yoy", description="经营增长"),
    F(factor_id="q_tr_yoy", display_name="营业总收入同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_tr_yoy", description="总收入增长"),
    F(factor_id="q_ocf_yoy", display_name="经营现金流同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_ocf_yoy", description="现金流增长"),
    F(factor_id="q_roe_yoy", display_name="ROE同比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_roe_yoy", description="效率提升"),
    F(factor_id="q_netprofitgrow_qoq", display_name="净利润环比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_netprofitgrow_qoq", description="短期加速"),
    F(factor_id="q_orgrow_qoq", display_name="营收环比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_orgrow_qoq", description="短期加速"),
    F(factor_id="q_opgrow_qoq", display_name="营业利润环比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_opgrow_qoq", description="短期加速"),
    F(factor_id="q_roegrow_qoq", display_name="ROE环比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_roegrow_qoq", description="短期加速"),
    F(factor_id="q_equitygrow_qoq", display_name="净资产环比增长率", category="fundamental",
      group_id="growth", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="q_equitygrow_qoq", description="资本积累"),
    # B4 质量因子
    F(factor_id="ocf_to_profit", display_name="经营现金流/净利润", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="ocf_to_profit", description="盈利质量"),
    F(factor_id="ocf_to_or", display_name="经营现金流/营业收入", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="ocf_to_or", description="收入质量"),
    F(factor_id="salescash_to_or", display_name="销售收现/营业收入", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="salescash_to_or", description="收入含金量"),
    F(factor_id="dtprofit_to_profit", display_name="扣非净利/净利润", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="dtprofit_to_profit", description="利润持续性"),
    F(factor_id="assets_turn", display_name="总资产周转率", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="assets_turn", description="运营效率"),
    F(factor_id="inv_turn", display_name="存货周转率", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="inv_turn", description="库存管理"),
    F(factor_id="ar_turn", display_name="应收账款周转率", category="fundamental",
      group_id="quality", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="ar_turn", description="回款效率"),
    F(factor_id="capitalized_to_da", display_name="资本支出/折旧摊销", category="fundamental",
      group_id="quality", direction="ASC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="capitalized_to_da", description="投资强度"),
    # B5 杠杆因子
    F(factor_id="debt_to_assets", display_name="资产负债率", category="fundamental",
      group_id="leverage", direction="ASC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="debt_to_assets", description="Barra DTOA"),
    F(factor_id="current_ratio", display_name="流动比率", category="fundamental",
      group_id="leverage", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="current_ratio", description="短期偿债"),
    F(factor_id="quick_ratio", display_name="速动比率", category="fundamental",
      group_id="leverage", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="quick_ratio", description="短期偿债"),
    F(factor_id="eqt_to_talcapital", display_name="归母权益/全部投入资本", category="fundamental",
      group_id="leverage", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="eqt_to_talcapital", description="Barra FMLEV"),
    F(factor_id="ebit_to_interest", display_name="利息保障倍数", category="fundamental",
      group_id="leverage", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="ebit_to_interest", description="偿债安全"),
    F(factor_id="ocf_to_debt", display_name="经营现金流/负债合计", category="fundamental",
      group_id="leverage", direction="DESC", data_origin="fina_indicator",
      compute_engine="cross_field", update_freq="quarterly", report_lag_days=120,
      dependencies="ocf_to_debt", description="现金偿债"),
    F(factor_id="mlev", display_name="市场杠杆", category="fundamental",
      group_id="leverage", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily_derived",
      dependencies="pb", description="Barra MLEV 简化近似: pb(=total_mv/total_equity), 数据模型无net_debt"),
]
