"""D类: 量价因子定义。"""

from xqtrader.domain.factor.definitions.factor_def import FactorDefinition as F

QUANTITATIVE_FACTORS: list[F] = [
    # D1 Alpha101
    F(factor_id="alpha_1", display_name="量价偏离极值日", category="quantitative",
      group_id="alpha101", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="vwap,open,volume", description="WQ#1"),
    F(factor_id="alpha_12", display_name="量增价跌反转", category="quantitative",
      group_id="alpha101", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=2,
      dependencies="volume,close,open", description="WQ#12"),
    F(factor_id="alpha_33", display_name="收盘开盘比衰减", category="quantitative",
      group_id="alpha101", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close,open", description="WQ#33"),
    F(factor_id="alpha_41", display_name="几何均价VWAP偏离", category="quantitative",
      group_id="alpha101", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily",
      dependencies="high,low,vwap", description="WQ#41"),
    F(factor_id="alpha_55", display_name="日内涨跌量相关", category="quantitative",
      group_id="alpha101", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close,open,volume", description="WQ#55"),
    F(factor_id="alpha_101", display_name="日内K线形态", category="quantitative",
      group_id="alpha101", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily",
      dependencies="close,open,high,low", description="WQ#101"),
    # D2 Alpha158
    F(factor_id="kmid_5", display_name="5日K线实体均值", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close,open", description="MA(5,(C-O)/O)"),
    F(factor_id="klen_5", display_name="5日K线振幅均值", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low,open", description="MA(5,(H-L)/O)"),
    F(factor_id="kup2_5", display_name="5日上影线占比均值", category="quantitative",
      group_id="alpha158", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,open,close,low", description="MA(5,(H-max(O,C))/(H-L))"),
    F(factor_id="klow2_5", display_name="5日下影线占比均值", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="low,open,close,high", description="MA(5,(min(O,C)-L)/(H-L))"),
    F(factor_id="rsv_9", display_name="9日随机值", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=9,
      dependencies="close,high,low", description="(C-L9)/(H9-L9)"),
    F(factor_id="cntp_20", display_name="20日上涨天数占比", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="count(C>C1,20)/20"),
    F(factor_id="sumd_20", display_name="20日净上涨贡献比", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="SUMP-SUMN"),
    F(factor_id="imax_20", display_name="20日最高价位置", category="quantitative",
      group_id="alpha158", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="argmax(C,20)/20"),
    F(factor_id="roc5_close", display_name="5日收盘变化率", category="quantitative",
      group_id="alpha158", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close", description="C/C[-5]-1"),
    F(factor_id="std20_close", display_name="20日收盘标准差", category="quantitative",
      group_id="alpha158", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="STD(20,C)/C"),
    # D3 资金流因子
    F(factor_id="cs_net_mf_amt", display_name="全部净流入额", category="quantitative",
      group_id="fund_flow", direction="DESC", data_origin="fund_flow_individual",
      compute_engine="cross_field", update_freq="daily",
      dependencies="net_mf_amt", description="资金净流入"),
    F(factor_id="cs_main_net_pct", display_name="主力净流入占比", category="quantitative",
      group_id="fund_flow", direction="DESC", data_origin="fund_flow_individual",
      compute_engine="cross_field", update_freq="daily",
      dependencies="main_net_pct", description="主力动向"),
    F(factor_id="huge_net_amt", display_name="超大单净流入", category="quantitative",
      group_id="fund_flow", direction="DESC", data_origin="fund_flow_individual",
      compute_engine="cross_field", update_freq="daily",
      dependencies="huge_net_amt", description="大资金"),
    F(factor_id="big_net_amt", display_name="大单净流入", category="quantitative",
      group_id="fund_flow", direction="DESC", data_origin="fund_flow_individual",
      compute_engine="cross_field", update_freq="daily",
      dependencies="big_net_amt", description="中大资金"),
    F(factor_id="main_net_amt", display_name="主力净流入额", category="quantitative",
      group_id="fund_flow", direction="DESC", data_origin="fund_flow_individual",
      compute_engine="cross_field", update_freq="daily",
      dependencies="main_net_amt", description="主力金额"),
    F(factor_id="z_main_net_pct", display_name="主力净流入Z-score", category="quantitative",
      group_id="fund_flow", direction="DESC", data_origin="computed",
      compute_engine="cross_zscore", update_freq="daily",
      dependencies="main_net_pct", description="截面标准化主力"),
    # D4 交互因子
    F(factor_id="mom_vol_cross", display_name="动量×波动", category="quantitative",
      group_id="interaction", direction="DESC", data_origin="computed",
      compute_engine="composite", update_freq="daily",
      dependencies="mom_20d,atr_ratio", description="非线性交互"),
    F(factor_id="adx_rsi_cross", display_name="ADX×RSI偏离", category="quantitative",
      group_id="interaction", direction="DESC", data_origin="computed",
      compute_engine="composite", update_freq="daily",
      dependencies="adx_14,rsi_14", description="趋势+超买"),
    F(factor_id="vol_ratio_mom_cross", display_name="量比×动量", category="quantitative",
      group_id="interaction", direction="DESC", data_origin="computed",
      compute_engine="composite", update_freq="daily",
      dependencies="cs_volume_ratio,mom_20d", description="量价配合"),
    F(factor_id="rsi_bbands_cross", display_name="RSI×布林位置", category="quantitative",
      group_id="interaction", direction="DESC", data_origin="computed",
      compute_engine="composite", update_freq="daily",
      dependencies="rsi_14,boll_width", description="超买+通道"),
    F(factor_id="macd_adx_cross", display_name="MACD×ADX", category="quantitative",
      group_id="interaction", direction="DESC", data_origin="computed",
      compute_engine="composite", update_freq="daily",
      dependencies="macd_hist,adx_14", description="趋势确认"),
    F(factor_id="vol_mom_accel_cross", display_name="波动×动量加速度", category="quantitative",
      group_id="interaction", direction="DESC", data_origin="computed",
      compute_engine="composite", update_freq="daily",
      dependencies="hist_vol_20,mom_20d", description="波动加速"),
]
