"""A类: 风险因子定义。"""

from xqtrader.domain.factor.definitions.factor_def import FactorDefinition as F

RISK_FACTORS: list[F] = [
    # A1 规模因子
    F(factor_id="cs_log_mv", display_name="对数总市值", category="risk",
      group_id="size", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="total_mv", description="Barra Size"),
    F(factor_id="nl_size", display_name="非线性规模", category="risk",
      group_id="size", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily",
      dependencies="cs_log_mv", description="Barra Non-linear Size, (log_mv)^3 正交化"),
    # A2 Beta因子
    F(factor_id="beta_250", display_name="250日Beta", category="risk",
      group_id="beta", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=250,
      dependencies="close,index_close", description="Barra Beta, 系统性风险暴露"),
    F(factor_id="beta_down", display_name="下行Beta", category="risk",
      group_id="beta", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=250,
      dependencies="close,index_close", description="负收益日Cov/Var, 不对称风险度量"),
    # A3 波动率因子
    F(factor_id="hist_vol_20", display_name="20日历史波动率", category="risk",
      group_id="volatility", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="STD(20,daily_ret)*sqrt(252)"),
    F(factor_id="hist_vol_60", display_name="60日历史波动率", category="risk",
      group_id="volatility", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=60,
      dependencies="close", description="STD(60,daily_ret)*sqrt(252)"),
    F(factor_id="downside_vol", display_name="下行波动率", category="risk",
      group_id="volatility", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=60,
      dependencies="close", description="STD(负收益日)*sqrt(252)"),
    F(factor_id="dastd", display_name="日收益标准差", category="risk",
      group_id="volatility", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=252,
      dependencies="close", description="Barra DASTD, 加权标准差(252日)"),
    F(factor_id="cmra", display_name="累计收益范围", category="risk",
      group_id="volatility", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=252,
      dependencies="close", description="Barra CMRA, log(1+max_cum)-log(1+min_cum)"),
    F(factor_id="atr_14", display_name="ATR(14)", category="risk",
      group_id="volatility", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=14,
      dependencies="high,low,close", description="绝对波动"),
    F(factor_id="atr_ratio", display_name="ATR/价格", category="risk",
      group_id="volatility", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=14,
      dependencies="high,low,close", description="标准化波动"),
    F(factor_id="boll_width", display_name="布林带宽度", category="risk",
      group_id="volatility", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="(upper-lower)/middle, 波动率代理"),
    # A4 流动性因子
    F(factor_id="cs_turnover", display_name="换手率", category="risk",
      group_id="liquidity", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="turnover_rate", description="日换手"),
    F(factor_id="turnover_f", display_name="流通换手率", category="risk",
      group_id="liquidity", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="turnover_rate_f", description="流通股换手"),
    F(factor_id="z_turnover", display_name="换手率Z-score", category="risk",
      group_id="liquidity", direction="DESC", data_origin="computed",
      compute_engine="cross_zscore", update_freq="daily",
      dependencies="turnover_rate", description="截面标准化换手率"),
    F(factor_id="amihud", display_name="Amihud非流动性", category="risk",
      group_id="liquidity", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close,amount", description="abs(ret)/amount, 价格冲击"),
    F(factor_id="cs_log_amount", display_name="对数成交额", category="risk",
      group_id="liquidity", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily",
      dependencies="amount", description="log(1+amount), 成交规模"),
    F(factor_id="cs_volume_ratio", display_name="量比", category="risk",
      group_id="liquidity", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="volume_ratio", description="量能异动"),
    F(factor_id="stom", display_name="月换手率", category="risk",
      group_id="liquidity", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=21,
      dependencies="turnover_rate", description="Barra STOM, sum(turnover,21)"),
    F(factor_id="stoq", display_name="季换手率", category="risk",
      group_id="liquidity", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=63,
      dependencies="turnover_rate", description="Barra STOQ, avg(STOM,3)"),
    F(factor_id="adv_20", display_name="20日均成交量", category="risk",
      group_id="liquidity", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="volume", description="MA(volume,20)"),
    F(factor_id="vol_osc", display_name="量振荡", category="risk",
      group_id="liquidity", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="volume", description="MA(V,5)/MA(V,20), 量能趋势"),
]
