"""C类: 技术因子定义。"""

from xqtrader.domain.factor.definitions.factor_def import FactorDefinition as F

TECHNICAL_FACTORS: list[F] = [
    # C1 动量/反转因子
    F(factor_id="cs_pct_chg", display_name="当日涨跌幅", category="technical",
      group_id="momentum", direction="DESC", data_origin="daily_indicator",
      compute_engine="cross_field", update_freq="daily_derived",
      dependencies="pct_chg", description="日度动量"),
    F(factor_id="mom_ret5d", display_name="5日动量收益", category="technical",
      group_id="momentum", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close", description="close/close[-5]-1"),
    F(factor_id="mom_20d", display_name="20日动量", category="technical",
      group_id="momentum", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="close/close[-20]-1"),
    F(factor_id="mom_60d", display_name="60日动量", category="technical",
      group_id="momentum", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=60,
      dependencies="close", description="close/close[-60]-1"),
    F(factor_id="roc_10", display_name="10日变化率", category="technical",
      group_id="momentum", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=10,
      dependencies="close", description="talib.ROC(10)"),
    F(factor_id="barra_momentum", display_name="Barra动量", category="technical",
      group_id="momentum", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=252,
      dependencies="close", description="12月收益(剔除近1月)"),
    F(factor_id="rev_5d", display_name="5日反转", category="technical",
      group_id="momentum", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close", description="-1*mom_ret5d"),
    F(factor_id="rev_20d", display_name="20日反转", category="technical",
      group_id="momentum", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="-1*roc_20"),
    F(factor_id="barra_strev", display_name="Barra短期反转", category="technical",
      group_id="momentum", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=21,
      dependencies="close", description="近1月收益*(-1)"),
    # C2 趋势因子
    F(factor_id="macd_dif", display_name="MACD-DIF线", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=35,
      dependencies="close", description="EMA(12)-EMA(26)"),
    F(factor_id="macd_dea", display_name="MACD-DEA线", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=35,
      dependencies="close", description="EMA(DIF,9)"),
    F(factor_id="macd_hist", display_name="MACD-柱状图", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=35,
      dependencies="close", description="DIF-DEA"),
    F(factor_id="adx_14", display_name="ADX(14)趋势强度", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=28,
      dependencies="high,low,close", description="talib.ADX(14)"),
    F(factor_id="adx_plus_di", display_name="+DI上升方向", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=14,
      dependencies="high,low,close", description="talib.PLUS_DI(14)"),
    F(factor_id="adx_minus_di", display_name="-DI下降方向", category="technical",
      group_id="trend", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=14,
      dependencies="high,low,close", description="talib.MINUS_DI(14)"),
    F(factor_id="sar", display_name="抛物线指标", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="high,low", description="talib.SAR"),
    F(factor_id="boll_upper", display_name="布林上轨", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="MA(20)+2σ"),
    F(factor_id="boll_middle", display_name="布林中轨", category="technical",
      group_id="trend", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="MA(20)"),
    F(factor_id="boll_lower", display_name="布林下轨", category="technical",
      group_id="trend", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="MA(20)-2σ"),
    # C3 超买超卖因子
    F(factor_id="rsi_14", display_name="RSI(14)", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=15,
      dependencies="close", description="talib.RSI(14)"),
    F(factor_id="kdj_k", display_name="KDJ-K值", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=9,
      dependencies="high,low,close", description="talib.STOCH(K=9,slowK=3)"),
    F(factor_id="kdj_d", display_name="KDJ-D值", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=9,
      dependencies="high,low,close", description="K的3日平滑"),
    F(factor_id="kdj_j", display_name="KDJ-J值", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=9,
      dependencies="high,low,close", description="3K-2D"),
    F(factor_id="bias_6", display_name="BIAS(6)乖离率", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=6,
      dependencies="close", description="(C-MA6)/MA6*100"),
    F(factor_id="bias_12", display_name="BIAS(12)乖离率", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=12,
      dependencies="close", description="(C-MA12)/MA12*100"),
    F(factor_id="bias_24", display_name="BIAS(24)乖离率", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=24,
      dependencies="close", description="(C-MA24)/MA24*100"),
    F(factor_id="cci_14", display_name="CCI(14)", category="technical",
      group_id="oscillator", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=14,
      dependencies="high,low,close", description="talib.CCI(14)"),
    F(factor_id="wr_14", display_name="WR(14)威廉指标", category="technical",
      group_id="oscillator", direction="ASC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=14,
      dependencies="high,low,close", description="talib.WILLR(14)"),
    # C4 均线因子
    F(factor_id="ma_5", display_name="MA5", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=5,
      dependencies="close", description="短期均线"),
    F(factor_id="ma_10", display_name="MA10", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=10,
      dependencies="close", description="短期均线"),
    F(factor_id="ma_20", display_name="MA20", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=20,
      dependencies="close", description="中期均线"),
    F(factor_id="ma_30", display_name="MA30", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=30,
      dependencies="close", description="中期均线"),
    F(factor_id="ma_60", display_name="MA60", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=60,
      dependencies="close", description="中长期均线"),
    F(factor_id="ma_120", display_name="MA120", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=120,
      dependencies="close", description="长期均线"),
    F(factor_id="ma_250", display_name="MA250年线", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=250,
      dependencies="close", description="长期均线"),
    F(factor_id="ema_12", display_name="EMA12", category="technical",
      group_id="ma", direction="DESC", data_origin="computed",
      compute_engine="plugin", update_freq="daily", min_periods=12,
      dependencies="close", description="指数均线"),
]
