"""QuantStats 绩效分析器 — 指标计算 + HTML 报告 + 中文补丁。

核心功能:
  1. 调用 quantstats.reports.metrics() 计算 75+ 项绩效指标
  2. 调用 quantstats.reports.html() 生成 HTML 报告
  3. 对 HTML 报告应用中文补丁（替换英文标签为中文）

设计原则:
  - 分析器无状态 — 输入 BacktestResult，输出 AnalysisReport
  - 中文补丁为纯字符串替换 — 不修改 quantstats 源码，版本升级兼容
  - 指标分两层：结构化 PerformanceMetrics（关键字段）+ raw dict（全量）
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd
import quantstats as qs

from framework.commons.logger import get_logger

from .constants import REPORT_DIR, TRADING_DAYS_PER_YEAR
from .engine import BacktestResult

logger = get_logger(__name__)


# ==================== 中文翻译表 ====================

# HTML 报告中 H3 章节标题的中文翻译
_H3_TRANSLATIONS: dict[str, str] = {
    "Key Performance Metrics": "关键绩效指标",
    "EOY Returns": "年末收益率",
    "Worst 10 Drawdowns": "最大 10 次回撤",
    "Returns": "收益率",
    "Drawdown": "回撤",
}

# HTML 报告中回撤表头的中文翻译
_TH_TRANSLATIONS: dict[str, str] = {
    "Started": "开始日期",
    "Recovered": "恢复日期",
    "Drawdown": "回撤幅度",
    "Days": "持续天数",
}

# 75 项绩效指标的英文 → 中文翻译
# 用于 HTML 报告中 <td>Label</td> 的替换
_METRIC_TRANSLATIONS: dict[str, str] = {
    "Start Period": "起始日期",
    "End Period": "结束日期",
    "Risk-Free Rate": "无风险利率",
    "Time in Market": "市场参与度",
    "Cumulative Return": "累计收益率",
    "CAGR﹪": "年化复合增长率",
    "Sharpe": "夏普比率",
    "Prob. Sharpe Ratio": "夏普比率概率",
    "Smart Sharpe": "智能夏普比率",
    "Sortino": "索提诺比率",
    "Smart Sortino": "智能索提诺比率",
    "Sortino/√2": "索提诺比率/√2",
    "Smart Sortino/√2": "智能索提诺比率/√2",
    "Omega": "欧米伽比率",
    "Max Drawdown": "最大回撤",
    "Max DD Date": "最大回撤日期",
    "Max DD Period Start": "最大回撤起始日",
    "Max DD Period End": "最大回撤结束日",
    "Longest DD Days": "最长回撤天数",
    "Volatility (ann.)": "年化波动率",
    "Calmar": "卡玛比率",
    "Skew": "偏度",
    "Kurtosis": "峰度",
    "Ulcer Performance Index": "溃疡绩效指数",
    "Risk-Adjusted Return": "风险调整收益",
    "Risk-Return Ratio": "风险收益比",
    "Avg. Return": "平均收益",
    "Avg. Win": "平均盈利",
    "Avg. Loss": "平均亏损",
    "Win/Loss Ratio": "盈亏比",
    "Profit Ratio": "盈利比率",
    "Expected Daily": "预期日收益",
    "Expected Monthly": "预期月收益",
    "Expected Yearly": "预期年收益",
    "Kelly Criterion": "凯利公式",
    "Risk of Ruin": "破产风险",
    "Daily Value-at-Risk": "日风险价值(VaR)",
    "Expected Shortfall (cVaR)": "条件风险价值(cVaR)",
    "Max Consecutive Wins": "最大连续盈利次数",
    "Max Consecutive Losses": "最大连续亏损次数",
    "Gain/Pain Ratio": "收益痛苦比",
    "Gain/Pain (1M)": "收益痛苦比(1月)",
    "Payoff Ratio": "赔付比率",
    "Profit Factor": "盈利因子",
    "Common Sense Ratio": "常识比率",
    "CPC Index": "CPC 指数",
    "Tail Ratio": "尾部比率",
    "Outlier Win Ratio": "异常盈利比",
    "Outlier Loss Ratio": "异常亏损比",
    "MTD": "本月收益",
    "3M": "近3月收益",
    "6M": "近6月收益",
    "YTD": "年初至今收益",
    "1Y": "近1年收益",
    "3Y (ann.)": "近3年年化收益",
    "5Y (ann.)": "近5年年化收益",
    "10Y (ann.)": "近10年年化收益",
    "All-time (ann.)": "历史年化收益",
    "Best Day": "最佳日收益",
    "Worst Day": "最差日收益",
    "Best Month": "最佳月收益",
    "Worst Month": "最差月收益",
    "Best Year": "最佳年收益",
    "Worst Year": "最差年收益",
    "Avg. Drawdown": "平均回撤",
    "Avg. Drawdown Days": "平均回撤天数",
    "Recovery Factor": "恢复因子",
    "Ulcer Index": "溃疡指数",
    "Serenity Index": "宁静指数",
    "Avg. Up Month": "平均上涨月",
    "Avg. Down Month": "平均下跌月",
    "Win Days": "日胜率",
    "Win Month": "月胜率",
    "Win Quarter": "季胜率",
    "Win Year": "年胜率",
}

# HTML 标题翻译
_HTML_TITLE_TRANSLATIONS: dict[str, str] = {
    "Tearsheet (generated by QuantStats)": "策略绩效报告（QuantStats 生成）",
    "Strategy Tearsheet": "策略绩效报告",
}


@dataclass
class PerformanceMetrics:
    """结构化绩效指标 — 从 QuantStats 75+ 项指标中提取关键字段。

    Attributes:
        cumulative_return: 累计收益率
        annual_return: 年化复合增长率（CAGR）
        sharpe_ratio: 夏普比率
        sortino_ratio: 索提诺比率
        max_drawdown: 最大回撤
        volatility: 年化波动率
        calmar_ratio: 卡玛比率
        win_rate: 日胜率
        profit_factor: 盈利因子
        skew: 偏度
        kurtosis: 峰度
        var_daily: 日风险价值（VaR）
        cvar: 条件风险价值（cVaR）
        best_day: 最佳日收益
        worst_day: 最差日收益
        best_month: 最佳月收益
        worst_month: 最差月收益
        raw: QuantStats 返回的全量指标字典
    """

    cumulative_return: float
    annual_return: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    volatility: float
    calmar_ratio: float
    win_rate: float
    profit_factor: float
    skew: float
    kurtosis: float
    var_daily: float
    cvar: float
    best_day: float
    worst_day: float
    best_month: float
    worst_month: float
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass
class AnalysisReport:
    """绩效分析报告。

    Attributes:
        strategy_id: 策略 ID
        start_date: 回测起始日期
        end_date: 回测结束日期
        metrics: 结构化绩效指标
        html_report_path: HTML 报告文件路径（None=未生成）
    """

    strategy_id: str
    start_date: date
    end_date: date
    metrics: PerformanceMetrics
    html_report_path: str | None = None

    def to_dict(self) -> dict[str, Any]:
        """转换为字典（供 API 响应使用）。"""
        return {
            "strategy_id": self.strategy_id,
            "start_date": self.start_date.isoformat(),
            "end_date": self.end_date.isoformat(),
            "metrics": {
                "cumulative_return": self.metrics.cumulative_return,
                "annual_return": self.metrics.annual_return,
                "sharpe_ratio": self.metrics.sharpe_ratio,
                "sortino_ratio": self.metrics.sortino_ratio,
                "max_drawdown": self.metrics.max_drawdown,
                "volatility": self.metrics.volatility,
                "calmar_ratio": self.metrics.calmar_ratio,
                "win_rate": self.metrics.win_rate,
                "profit_factor": self.metrics.profit_factor,
                "skew": self.metrics.skew,
                "kurtosis": self.metrics.kurtosis,
                "var_daily": self.metrics.var_daily,
                "cvar": self.metrics.cvar,
                "best_day": self.metrics.best_day,
                "worst_day": self.metrics.worst_day,
                "best_month": self.metrics.best_month,
                "worst_month": self.metrics.worst_month,
            },
            "html_report_path": self.html_report_path,
        }


class QuantStatsAnalyzer:
    """QuantStats 绩效分析器 — 指标计算 + HTML 报告 + 中文补丁。

    用法:
        analyzer = QuantStatsAnalyzer()
        report = analyzer.analyze(backtest_result, output_dir=Path("reports/backtest"))
        print(report.metrics.sharpe_ratio)
        print(report.html_report_path)
    """

    def analyze(
        self,
        result: BacktestResult,
        output_dir: Path | None = None,
        benchmark: pd.Series | None = None,
        rf: float = 0.0,
    ) -> AnalysisReport:
        """分析回测结果，生成绩效指标 + HTML 报告。

        Args:
            result: 回测结果（含 daily_returns）
            output_dir: HTML 报告输出目录（None=使用默认目录）
            benchmark: 基准收益率序列（None=无基准）
            rf: 无风险利率（年化小数，如 0.02 = 2%）

        Returns:
            AnalysisReport: 绩效分析报告
        """
        logger.info(
            f"开始绩效分析 | strategy={result.strategy_id} | "
            f"days={len(result.daily_returns)}",
        )

        daily_returns = self._prepare_returns(result.daily_returns)
        metrics = self._compute_metrics(daily_returns, benchmark=benchmark, rf=rf)

        html_path = self._generate_html_report(
            result=result,
            daily_returns=daily_returns,
            output_dir=output_dir,
            benchmark=benchmark,
            rf=rf,
        )

        logger.info(
            f"绩效分析完成 | strategy={result.strategy_id} | "
            f"sharpe={metrics.sharpe_ratio:.4f} | "
            f"max_dd={metrics.max_drawdown:.4%} | "
            f"html={html_path}",
        )

        return AnalysisReport(
            strategy_id=result.strategy_id,
            start_date=result.start_date,
            end_date=result.end_date,
            metrics=metrics,
            html_report_path=str(html_path) if html_path else None,
        )

    # ==================== 指标计算 ====================

    def _compute_metrics(
        self,
        daily_returns: pd.Series,
        benchmark: pd.Series | None = None,
        rf: float = 0.0,
    ) -> PerformanceMetrics:
        """调用 QuantStats 计算全量指标，提取结构化字段。"""
        raw_df = qs.reports.metrics(
            daily_returns,
            benchmark=benchmark,
            rf=rf,
            display=False,
            mode="full",
            periods_per_year=TRADING_DAYS_PER_YEAR,
        )

        # QuantStats 返回 DataFrame，取第一列（Strategy 列）
        raw_dict: dict[str, Any] = {}
        for idx, val in zip(raw_df.index, raw_df.iloc[:, 0]):
            raw_dict[str(idx)] = val

        return PerformanceMetrics(
            cumulative_return=self._safe_float(raw_dict.get("Cumulative Return")),
            annual_return=self._safe_float(raw_dict.get("CAGR﹪")),
            sharpe_ratio=self._safe_float(raw_dict.get("Sharpe")),
            sortino_ratio=self._safe_float(raw_dict.get("Sortino")),
            max_drawdown=self._safe_float(raw_dict.get("Max Drawdown")),
            volatility=self._safe_float(raw_dict.get("Volatility (ann.)")),
            calmar_ratio=self._safe_float(raw_dict.get("Calmar")),
            win_rate=self._safe_float(raw_dict.get("Win Days")),
            profit_factor=self._safe_float(raw_dict.get("Profit Factor")),
            skew=self._safe_float(raw_dict.get("Skew")),
            kurtosis=self._safe_float(raw_dict.get("Kurtosis")),
            var_daily=self._safe_float(raw_dict.get("Daily Value-at-Risk")),
            cvar=self._safe_float(raw_dict.get("Expected Shortfall (cVaR)")),
            best_day=self._safe_float(raw_dict.get("Best Day")),
            worst_day=self._safe_float(raw_dict.get("Worst Day")),
            best_month=self._safe_float(raw_dict.get("Best Month")),
            worst_month=self._safe_float(raw_dict.get("Worst Month")),
            raw=raw_dict,
        )

    # ==================== HTML 报告生成 ====================

    def _generate_html_report(
        self,
        result: BacktestResult,
        daily_returns: pd.Series,
        output_dir: Path | None,
        benchmark: pd.Series | None,
        rf: float,
    ) -> Path | None:
        """生成 HTML 报告并应用中文补丁。"""
        report_dir = output_dir or REPORT_DIR
        report_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{result.strategy_id}_{result.start_date}_{result.end_date}.html"
        output_path = report_dir / filename

        title = f"策略绩效报告 — {result.strategy_id}"

        try:
            # quantstats.reports.html() 直接写入文件（output=路径）
            # 返回 None，HTML 内容在文件中
            qs.reports.html(
                daily_returns,
                benchmark=benchmark,
                rf=rf,
                title=title,
                output=str(output_path),
                compounded=True,
                periods_per_year=TRADING_DAYS_PER_YEAR,
            )

            # 读取生成的 HTML，应用中文补丁后写回
            raw_html = output_path.read_text(encoding="utf-8")
            patched_html = self._apply_chinese_patch(raw_html)
            output_path.write_text(patched_html, encoding="utf-8")

            logger.info(f"HTML 报告已生成: {output_path}")
            return output_path

        except Exception as e:
            logger.error(f"HTML 报告生成失败: {e}", exc_info=True)
            return None

    # ==================== 中文补丁 ====================

    def _apply_chinese_patch(self, html: str) -> str:
        """对 HTML 报告应用中文补丁 — 替换英文标签为中文。

        补丁策略:
          1. 替换 <title> 标签内容
          2. 替换 <h3> 章节标题
          3. 替换 <th> 表头
          4. 替换 <td>Label</td> 中的指标名
        """
        patched = html

        # 1. 替换 HTML <title> 标签
        for en, cn in _HTML_TITLE_TRANSLATIONS.items():
            patched = patched.replace(f"<title>{en}</title>", f"<title>{cn}</title>")

        # 2. 替换 <h3> 章节标题
        for en, cn in _H3_TRANSLATIONS.items():
            patched = patched.replace(f">{en}<", f">{cn}<")

        # 3. 替换 <th> 表头
        for en, cn in _TH_TRANSLATIONS.items():
            patched = patched.replace(f"<th>{en}</th>", f"<th>{cn}</th>")

        # 4. 替换 <td> 指标标签
        for en, cn in _METRIC_TRANSLATIONS.items():
            patched = patched.replace(f"<td>{en}</td>", f"<td>{cn}</td>")

        return patched

    # ==================== 工具方法 ====================

    @staticmethod
    def _prepare_returns(daily_returns: pd.Series) -> pd.Series:
        """准备收益率序列 — 确保 index 为 DatetimeIndex、name 为 strategy。"""
        if daily_returns.empty:
            return daily_returns

        prepared = daily_returns.copy()
        if not isinstance(prepared.index, pd.DatetimeIndex):
            prepared.index = pd.to_datetime(prepared.index)
        prepared.name = "strategy"
        return prepared

    @staticmethod
    def _safe_float(value: Any) -> float:
        """安全转换为 float — 处理 None / NaN / 字符串。"""
        if value is None:
            return 0.0
        try:
            result = float(value)
            if pd.isna(result):
                return 0.0
            return result
        except (ValueError, TypeError):
            return 0.0
