"""财务指标 ORM 模型。"""

# ruff: noqa: E501

from datetime import date

from sqlalchemy import Date, Float, String
from sqlalchemy.orm import Mapped, mapped_column

from framework.dal.base import Base


class FinancialIndicator(Base):
    """财务指标表"""

    __bind_key__ = "stock"
    __tablename__ = "sdc_financial_indicator"

    symbol: Mapped[str] = mapped_column(String(20), primary_key=True, comment="TS股票代码")
    ann_date: Mapped[date | None] = mapped_column(Date, comment="公告日期")
    end_date: Mapped[date] = mapped_column(Date, primary_key=True, comment="报告期")
    update_flag: Mapped[str] = mapped_column(String(1), primary_key=True, comment="更新标识(1最新)")
    eps: Mapped[float | None] = mapped_column(Float, comment="基本每股收益")
    dt_eps: Mapped[float | None] = mapped_column(Float, comment="稀释每股收益")
    total_revenue_ps: Mapped[float | None] = mapped_column(Float, comment="每股营业总收入")
    revenue_ps: Mapped[float | None] = mapped_column(Float, comment="每股营业收入")
    capital_rese_ps: Mapped[float | None] = mapped_column(Float, comment="每股资本公积")
    surplus_rese_ps: Mapped[float | None] = mapped_column(Float, comment="每股盈余公积")
    undist_profit_ps: Mapped[float | None] = mapped_column(Float, comment="每股未分配利润")
    extra_item: Mapped[float | None] = mapped_column(Float, comment="非经常性损益")
    profit_dedt: Mapped[float | None] = mapped_column(Float, comment="扣除非经常性损益后的净利润")
    gross_margin: Mapped[float | None] = mapped_column(Float, comment="毛利")
    current_ratio: Mapped[float | None] = mapped_column(Float, comment="流动比率")
    quick_ratio: Mapped[float | None] = mapped_column(Float, comment="速动比率")
    cash_ratio: Mapped[float | None] = mapped_column(Float, comment="保守速动比率")
    invturn_days: Mapped[float | None] = mapped_column(Float, comment="存货周转天数")
    arturn_days: Mapped[float | None] = mapped_column(Float, comment="应收账款周转天数")
    inv_turn: Mapped[float | None] = mapped_column(Float, comment="存货周转率")
    ar_turn: Mapped[float | None] = mapped_column(Float, comment="应收账款周转率")
    ca_turn: Mapped[float | None] = mapped_column(Float, comment="流动资产周转率")
    fa_turn: Mapped[float | None] = mapped_column(Float, comment="固定资产周转率")
    assets_turn: Mapped[float | None] = mapped_column(Float, comment="总资产周转率")
    op_income: Mapped[float | None] = mapped_column(Float, comment="经营活动净收益")
    valuechange_income: Mapped[float | None] = mapped_column(Float, comment="价值变动净收益")
    interst_income: Mapped[float | None] = mapped_column(Float, comment="利息费用")
    daa: Mapped[float | None] = mapped_column(Float, comment="折旧与摊销")
    ebit: Mapped[float | None] = mapped_column(Float, comment="息税前利润")
    ebitda: Mapped[float | None] = mapped_column(Float, comment="息税折旧摊销前利润")
    fcff: Mapped[float | None] = mapped_column(Float, comment="企业自由现金流量")
    fcfe: Mapped[float | None] = mapped_column(Float, comment="股权自由现金流量")
    current_exint: Mapped[float | None] = mapped_column(Float, comment="无息流动负债")
    noncurrent_exint: Mapped[float | None] = mapped_column(Float, comment="无息非流动负债")
    interestdebt: Mapped[float | None] = mapped_column(Float, comment="带息债务")
    netdebt: Mapped[float | None] = mapped_column(Float, comment="净债务")
    tangible_asset: Mapped[float | None] = mapped_column(Float, comment="有形资产")
    working_capital: Mapped[float | None] = mapped_column(Float, comment="营运资金")
    networking_capital: Mapped[float | None] = mapped_column(Float, comment="营运流动资本")
    invest_capital: Mapped[float | None] = mapped_column(Float, comment="全部投入资本")
    retained_earnings: Mapped[float | None] = mapped_column(Float, comment="留存收益")
    diluted2_eps: Mapped[float | None] = mapped_column(Float, comment="期末摊薄每股收益")
    bps: Mapped[float | None] = mapped_column(Float, comment="每股净资产")
    ocfps: Mapped[float | None] = mapped_column(Float, comment="每股经营活动产生的现金流量净额")
    retainedps: Mapped[float | None] = mapped_column(Float, comment="每股留存收益")
    cfps: Mapped[float | None] = mapped_column(Float, comment="每股现金流量净额")
    ebit_ps: Mapped[float | None] = mapped_column(Float, comment="每股息税前利润")
    fcff_ps: Mapped[float | None] = mapped_column(Float, comment="每股企业自由现金流量")
    fcfe_ps: Mapped[float | None] = mapped_column(Float, comment="每股股东自由现金流量")
    netprofit_margin: Mapped[float | None] = mapped_column(Float, comment="销售净利率")
    grossprofit_margin: Mapped[float | None] = mapped_column(Float, comment="销售毛利率")
    cogs_of_sales: Mapped[float | None] = mapped_column(Float, comment="销售成本率")
    expense_of_sales: Mapped[float | None] = mapped_column(Float, comment="销售期间费用率")
    profit_to_gr: Mapped[float | None] = mapped_column(Float, comment="净利润/营业总收入")
    saleexp_to_gr: Mapped[float | None] = mapped_column(Float, comment="销售费用/营业总收入")
    adminexp_of_gr: Mapped[float | None] = mapped_column(Float, comment="管理费用/营业总收入")
    finaexp_of_gr: Mapped[float | None] = mapped_column(Float, comment="财务费用/营业总收入")
    impai_ttm: Mapped[float | None] = mapped_column(Float, comment="资产减值损失/营业总收入")
    gc_of_gr: Mapped[float | None] = mapped_column(Float, comment="营业总成本/营业总收入")
    op_of_gr: Mapped[float | None] = mapped_column(Float, comment="营业利润/营业总收入")
    ebit_of_gr: Mapped[float | None] = mapped_column(Float, comment="息税前利润/营业总收入")
    roe: Mapped[float | None] = mapped_column(Float, comment="净资产收益率")
    roe_waa: Mapped[float | None] = mapped_column(Float, comment="加权平均净资产收益率")
    roe_dt: Mapped[float | None] = mapped_column(Float, comment="净资产收益率(扣除非经常损益)")
    roa: Mapped[float | None] = mapped_column(Float, comment="总资产报酬率")
    npta: Mapped[float | None] = mapped_column(Float, comment="总资产净利润")
    roic: Mapped[float | None] = mapped_column(Float, comment="投入资本回报率")
    roe_yearly: Mapped[float | None] = mapped_column(Float, comment="年化净资产收益率")
    roa2_yearly: Mapped[float | None] = mapped_column(Float, comment="年化总资产报酬率")
    roe_avg: Mapped[float | None] = mapped_column(Float, comment="平均净资产收益率(增发条件)")
    opincome_of_ebt: Mapped[float | None] = mapped_column(Float, comment="经营活动净收益/利润总额")
    investincome_of_ebt: Mapped[float | None] = mapped_column(Float, comment="价值变动净收益/利润总额")
    n_op_profit_of_ebt: Mapped[float | None] = mapped_column(Float, comment="营业外收支净额/利润总额")
    tax_to_ebt: Mapped[float | None] = mapped_column(Float, comment="所得税/利润总额")
    dtprofit_to_profit: Mapped[float | None] = mapped_column(Float, comment="扣非后净利润/净利润")
    salescash_to_or: Mapped[float | None] = mapped_column(Float, comment="销售商品劳务收到现金/营业收入")
    ocf_to_or: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/营业收入")
    ocf_to_opincome: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/经营活动净收益")
    capitalized_to_da: Mapped[float | None] = mapped_column(Float, comment="资本支出/折旧和摊销")
    debt_to_assets: Mapped[float | None] = mapped_column(Float, comment="资产负债率")
    assets_to_eqt: Mapped[float | None] = mapped_column(Float, comment="权益乘数")
    dp_assets_to_eqt: Mapped[float | None] = mapped_column(Float, comment="权益乘数(杜邦分析)")
    ca_to_assets: Mapped[float | None] = mapped_column(Float, comment="流动资产/总资产")
    nca_to_assets: Mapped[float | None] = mapped_column(Float, comment="非流动资产/总资产")
    tbassets_to_totalassets: Mapped[float | None] = mapped_column(Float, comment="有形资产/总资产")
    int_to_talcap: Mapped[float | None] = mapped_column(Float, comment="带息债务/全部投入资本")
    eqt_to_talcapital: Mapped[float | None] = mapped_column(Float, comment="归属母公司股东权益/全部投入资本")
    currentdebt_to_debt: Mapped[float | None] = mapped_column(Float, comment="流动负债/负债合计")
    longdeb_to_debt: Mapped[float | None] = mapped_column(Float, comment="非流动负债/负债合计")
    ocf_to_shortdebt: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/流动负债")
    debt_to_eqt: Mapped[float | None] = mapped_column(Float, comment="产权比率")
    eqt_to_debt: Mapped[float | None] = mapped_column(Float, comment="归属母公司股东权益/负债合计")
    eqt_to_interestdebt: Mapped[float | None] = mapped_column(Float, comment="归属母公司股东权益/带息债务")
    tangibleasset_to_debt: Mapped[float | None] = mapped_column(Float, comment="有形资产/负债合计")
    tangasset_to_intdebt: Mapped[float | None] = mapped_column(Float, comment="有形资产/带息债务")
    tangibleasset_to_netdebt: Mapped[float | None] = mapped_column(Float, comment="有形资产/净债务")
    ocf_to_debt: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/负债合计")
    ocf_to_interestdebt: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/带息债务")
    ocf_to_netdebt: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/净债务")
    ebit_to_interest: Mapped[float | None] = mapped_column(Float, comment="息税前利润/利息费用")
    longdebt_to_workingcapital: Mapped[float | None] = mapped_column(Float, comment="非流动负债/营运资金")
    ebitda_to_debt: Mapped[float | None] = mapped_column(Float, comment="息税折旧摊销前利润/负债合计")
    turn_days: Mapped[float | None] = mapped_column(Float, comment="营业周期")
    roa_yearly: Mapped[float | None] = mapped_column(Float, comment="年化总资产净利润")
    roa_dp: Mapped[float | None] = mapped_column(Float, comment="总资产报酬率(杜邦分析)")
    fixed_assets: Mapped[float | None] = mapped_column(Float, comment="固定资产")
    profit_prefin_exp: Mapped[float | None] = mapped_column(Float, comment="扣减财务费用前利润")
    non_op_profit: Mapped[float | None] = mapped_column(Float, comment="营业外收支净额")
    op_to_ebt: Mapped[float | None] = mapped_column(Float, comment="营业利润/利润总额")
    nop_to_ebt: Mapped[float | None] = mapped_column(Float, comment="营业外收支净额/利润总额")
    ocf_to_profit: Mapped[float | None] = mapped_column(Float, comment="经营活动现金流量净额/净利润")
    cash_to_liqdebt: Mapped[float | None] = mapped_column(Float, comment="货币资金/流动负债")
    cash_to_liqdebt_withinterest: Mapped[float | None] = mapped_column(Float, comment="货币资金/带息流动负债")
    op_to_liqdebt: Mapped[float | None] = mapped_column(Float, comment="经营活动净收益/流动负债")
    op_to_debt: Mapped[float | None] = mapped_column(Float, comment="经营活动净收益/负债合计")
    roic_yearly: Mapped[float | None] = mapped_column(Float, comment="年化投入资本回报率")
    total_fa_trun: Mapped[float | None] = mapped_column(Float, comment="固定资产周转率")
    profit_to_op: Mapped[float | None] = mapped_column(Float, comment="净利润/营业利润")
    # ── 非 Tushare fina_indicator 字段（当前 API 不返回，保留供其他数据源填充） ──
    q_opincome_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度经营利润环比增长率")
    q_investincome_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度投资收益环比增长率")
    q_dtprofit_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度扣非净利润环比增长率")
    q_roe_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度净资产收益率环比增长率")
    q_equity_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度净资产环比增长率")
    q_assets_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度总资产环比增长率")
    q_tr_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度营业总收入同比增长率")
    q_or_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度营业收入同比增长率")
    q_gr_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度营业总收入同比增长率")
    q_op_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度营业利润同比增长率")
    q_profit_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度利润总额同比增长率")
    q_netprofit_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度净利润同比增长率")
    q_dtprofit_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度扣非净利润同比增长率")
    q_ocf_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度经营现金流同比增长率")
    q_roe_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度净资产收益率同比增长率")
    q_assets_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度总资产同比增长率")
    q_equity_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度净资产同比增长率")
    q_trgrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度营业总收入环比增长率")
    q_orgrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度营业收入环比增长率")
    q_opgrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度经营利润环比增长率")
    q_profitgrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度利润总额环比增长率")
    q_netprofitgrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度净利润环比增长率")
    q_ocfgrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度经营现金流环比增长率")
    q_roegrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度净资产收益率环比增长率")
    q_equitygrow_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度净资产环比增长率")
    # ── 单季度原始指标 ──
    q_opincome: Mapped[float | None] = mapped_column(Float, comment="单季度经营利润")
    q_investincome: Mapped[float | None] = mapped_column(Float, comment="单季度投资收益")
    q_dtprofit: Mapped[float | None] = mapped_column(Float, comment="单季度扣非净利润")
    q_eps: Mapped[float | None] = mapped_column(Float, comment="单季度每股收益")
    q_netprofit_margin: Mapped[float | None] = mapped_column(Float, comment="单季度销售净利率")
    q_gsprofit_margin: Mapped[float | None] = mapped_column(Float, comment="单季度销售毛利率")
    q_exp_to_sales: Mapped[float | None] = mapped_column(Float, comment="单季度期间费用率")
    q_profit_to_gr: Mapped[float | None] = mapped_column(Float, comment="单季度净利润/营业总收入")
    q_saleexp_to_gr: Mapped[float | None] = mapped_column(Float, comment="单季度销售费用/营业总收入")
    q_adminexp_to_gr: Mapped[float | None] = mapped_column(Float, comment="单季度管理费用/营业总收入")
    q_finaexp_to_gr: Mapped[float | None] = mapped_column(Float, comment="单季度财务费用/营业总收入")
    q_impair_to_gr_ttm: Mapped[float | None] = mapped_column(Float, comment="单季度资产减值损失/营业总收入TTM")
    q_gc_to_gr: Mapped[float | None] = mapped_column(Float, comment="单季度营业总成本/营业总收入")
    q_op_to_gr: Mapped[float | None] = mapped_column(Float, comment="单季度营业利润/营业总收入")
    q_roe: Mapped[float | None] = mapped_column(Float, comment="单季度净资产收益率")
    q_dt_roe: Mapped[float | None] = mapped_column(Float, comment="单季度扣非净资产收益率")
    q_npta: Mapped[float | None] = mapped_column(Float, comment="单季度总资产净利润")
    q_opincome_to_ebt: Mapped[float | None] = mapped_column(Float, comment="单季度经营利润/利润总额")
    q_investincome_to_ebt: Mapped[float | None] = mapped_column(Float, comment="单季度投资收益/利润总额")
    q_dtprofit_to_profit: Mapped[float | None] = mapped_column(Float, comment="单季度扣非净利润/净利润")
    q_salescash_to_or: Mapped[float | None] = mapped_column(Float, comment="单季度销售收现/营业收入")
    q_ocf_to_sales: Mapped[float | None] = mapped_column(Float, comment="单季度经营现金流/营业收入")
    q_ocf_to_or: Mapped[float | None] = mapped_column(Float, comment="单季度经营现金流/营业总收入")
    # ── 年度同比增长率 ──
    basic_eps_yoy: Mapped[float | None] = mapped_column(Float, comment="基本每股收益同比增长率")
    dt_eps_yoy: Mapped[float | None] = mapped_column(Float, comment="稀释每股收益同比增长率")
    cfps_yoy: Mapped[float | None] = mapped_column(Float, comment="每股现金流同比增长率")
    op_yoy: Mapped[float | None] = mapped_column(Float, comment="营业利润同比增长率")
    ebt_yoy: Mapped[float | None] = mapped_column(Float, comment="利润总额同比增长率")
    netprofit_yoy: Mapped[float | None] = mapped_column(Float, comment="净利润同比增长率")
    dt_netprofit_yoy: Mapped[float | None] = mapped_column(Float, comment="扣非净利润同比增长率")
    ocf_yoy: Mapped[float | None] = mapped_column(Float, comment="经营现金流同比增长率")
    roe_yoy: Mapped[float | None] = mapped_column(Float, comment="净资产收益率同比增长率")
    bps_yoy: Mapped[float | None] = mapped_column(Float, comment="每股净资产同比增长率")
    assets_yoy: Mapped[float | None] = mapped_column(Float, comment="总资产同比增长率")
    eqt_yoy: Mapped[float | None] = mapped_column(Float, comment="净资产同比增长率")
    tr_yoy: Mapped[float | None] = mapped_column(Float, comment="营业总收入同比增长率")
    or_yoy: Mapped[float | None] = mapped_column(Float, comment="营业收入同比增长率")
    # ── 单季度同比/环比增长率 ──
    q_gr_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度营业总收入环比增长率")
    q_sales_yoy: Mapped[float | None] = mapped_column(Float, comment="单季度营业收入同比增长率")
    q_sales_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度营业收入环比增长率")
    q_op_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度营业利润环比增长率")
    q_profit_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度利润总额环比增长率")
    q_netprofit_qoq: Mapped[float | None] = mapped_column(Float, comment="单季度净利润环比增长率")
    # ── 其他 ──
    equity_yoy: Mapped[float | None] = mapped_column(Float, comment="净资产同比增长率")
    rd_exp: Mapped[float | None] = mapped_column(Float, comment="研发费用")

    __table_args__ = ({"comment": "财务指标表 - 存储上市公司财务指标数据(盈利/成长/偿债/运营等)"},)
